const texts = [{
    text: "The sun was beginning to set, casting a warm, golden glow over the bustling cityscape. People hurried by, each caught up in their own world, yet contributing to the symphony of urban life. Street vendors called out their wares, enticing passersby with the smell of freshly cooked food. Children laughed and played at the nearby park, their joyous sounds a stark contrast to the honking cars and distant sirens. Amidst the chaos, a sense of harmony prevailed, as if each element knew its place in the grand tapestry of the city. The air was filled with a sense of possibility, a feeling that anything could happen in this vibrant, ever-changing metropolis.",
    time: 60,
},{
    text: "Typing can be a fun and valuable skill to develop, whether for personal use or professional needs. Practicing regularly can enhance your speed and accuracy, allowing you to complete tasks more efficiently. Begin by focusing on proper hand placement and finger movement to improve muscle memory. Over time, you will notice a significant improvement in your typing abilities. Additionally, consider using various typing software and online resources to track your progress and set new goals. Remember, consistency is key, so make typing practice a part of your daily routine to see the best results!",
    time: 60,
},{
    text: "Once upon a time in a small, serene village nestled between rolling hills and lush forests, there was a rumor of a hidden treasure buried deep within the woods. The villagers spoke in hushed tones about an ancient map that revealed the treasure's location, passed down through generations. Adventure-seekers from near and far ventured into the dense forest, hoping to unearth the riches. Despite the allure of wealth, the forest remained largely undisturbed, as most who entered never returned or came back empty-handed. The mystery remained a captivating tale, inspiring dreams and sparking wonder in the hearts of all who lived in the quaint, tranquil village.",
    time: 60,
},{
    text: "The morning dew clung to the grass as the city slowly came to life. People walked briskly to their destinations, coffee in hand, while street cleaners worked tirelessly. The smell of freshly baked bread wafted through the air, tempting the early risers. In the midst of the hustle and bustle, a lone artist sat by the fountain, capturing the scene on his canvas. The harmony of the urban morning was a perfect blend of motion and stillness, a prelude to the day's unfolding tapestry.",
    time: 60,
},{
    text: "Learning to code can be an exciting journey filled with challenges and triumphs. Start by familiarizing yourself with basic concepts and syntax. As you progress, practice regularly by working on small projects or solving coding challenges. Utilizing online platforms and resources can greatly speed up your learning process. Remember, persistence and curiosity are essential. Embrace mistakes as learning opportunities and celebrate your progress along the way.",
    time: 60,
},{
    text: "The night was calm, the stars twinkling brightly against the velvety sky. The village was cloaked in silence,a stark contrast to the distant chirping of nocturnal insects. Families gathered around fireplaces, sharing stories passed down through generations. Elves were rumored to wander through the forest under the moonlight, their magical presence adding to the village's mystique. The serenity of the night filled the hearts of the inhabitants with a sense of peace and wonder, as they drifted into dreams shaped by tales of old.",
    time: 60,
 },,{
    text: "Exploring the world of photography opens up endless creative possibilities. Begin by understanding the basics of composition, lighting, and camera settings. Practice by taking photos in different environments, experimenting with angles and perspectives. Join photography communities to share your work and gain valuable feedback. Over time, your skills will grow, allowing you to capture moments with more precision and artistry.",
    time: 60,
},{
    text: "The first snowfall of the season blanketed the city in a pristine layer of white. Children rushed outside, eager to build snowmen and engage in snowball fights. Adults navigated the icy streets with a mix of caution and nostalgia. The air was crisp, and the scent of pine and wood smoke filled the atmosphere. Despite the freezing temperatures, there was warmth in the laughter and camaraderie that the snow day brought.",
    time: 60,
},{
    text: "Gardening can be a therapeutic and rewarding hobby. Start with easy-to-grow plants to build your confidence. Pay attention to the specific needs of each species, from sunlight to watering routines. Over time, you'll understand your garden's unique ecosystem. Not only does gardening beautify your space, but it also provides a sense of accomplishment as you watch your plants thrive and bloom.",
    time: 60,
},{
    text: "The market was alive with colors and sounds as vendors shouted their offers and customers haggled for the best deals. The smell of spices and fresh produce filled the air. Musicians played lively tunes, adding to the vibrant atmosphere. Amidst the clamor, friendships were forged and stories exchanged. The market was more than a place to buy goods; it was a social hub that knit the community together.",
    time: 60,
},{
    text: "Reading is a gateway to endless worlds and possibilities. Make it a habit to read a little every day, exploring various genres and authors. Not only does it improve your vocabulary and comprehension skills, but it also broadens your perspective. Join a book club or discussion group to share insights and discover new books. Embrace reading as a lifelong journey of growth and enjoyment.",
    time: 60,
},{
    text: "The sun dipped below the horizon, painting the sky in hues of pink and orange. Couples strolled along the beach, leaving footprints in the wet sand. The rhythmic waves whispered secrets as they caressed the shore. Bonfires flickered to life, casting a warm glow on faces illuminated with joy and laughter. As the day came to an end, a sense of contentment and wonder lingered in the cool evening air.",
    time: 60,
},{
    text: "Cooking can be a delightful and creative adventure. Start by mastering basic recipes and gradually experiment with new ingredients and techniques. Pay attention to flavors and textures, tweaking recipes to suit your taste. Cooking not only nourishes the body but also provides a platform for creativity and expression. Share your creations with others, making meals a communal and enriching experience.",
    time: 60,
},{
    text: "The sun was beginning to set over the tranquil lake, casting a golden hue across the water's surface. The air was cool and crisp, a perfect evening to reflect on the day's events. Birds chirped softly in the distance, their calls blending harmoniously with the gentle rustling of leaves in the breeze. A family of ducks glided effortlessly across the water, creating ripples that seemed to dance in the fading light. As I sat on the wooden dock, the wood warm beneath me, I felt a deep sense of peace and contentment. Life's worries seemed to drift away with the sound of the waves gently lapping against the shore. The sky transformed into a tapestry of colors, with hues of pink, orange, and purple blending seamlessly together. It was moments like these that reminded me of the simple beauty in the world. No matter how chaotic life might become, there is always a place for tranquility and calm. Taking a deep breath, I savored the moment, knowing that such experiences are precious and rare. This evening by the lake would be a cherished memory, a reminder to find joy in the serene moments of life.",
    time: 300,
},{
    text: "The gentle autumn breeze whispered through the amber leaves, creating a soothing rustle that filled the air with a sense of calm. As Lucy strolled down the tree-lined path, she admired the vibrant tapestry of reds, oranges, and yellows that draped the landscape. Each step she took crunched against the fallen leaves beneath her feet, releasing a nostalgic scent that reminded her of childhood days spent playing in the park. The sun, low in the sky, cast long, golden shadows that danced and flickered with each movement. Birds chirped melodiously from their perches, adding a delightful soundtrack to the serene scene. Lucy paused to take it all in, closing her eyes and breathing deeply, allowing the tranquility to wash over her. For a moment, time seemed to stand still, wrapped in the gentle embrace of nature's beauty. As she continued her walk, a sense of peace and gratitude filled her heart, a reminder of the simple joys that could be found in the changing seasons. Autumn had arrived, and with it, a sense of renewal and reflection that whispered of new beginnings and endless possibilities.",
    time: 300,
},{
    text: "The autumnal zephyr sighed among the gold-hued foliage, producing a calming rustle that permeated the atmosphere with serenity. As Jason wandered along the leafy promenade, he reveled in the vivid mosaic of crimsons, tangerines, and canaries adorning the environment. Each stride he made upon the carpet of leaves elicited a crunch and an earthy scent that evoked memories of youth spent in outdoor enjoyment. The sun hovered close to the horizon, casting extended, honey-colored shadows that waltzed and swayed with every motion. Songbirds serenaded from their arboreal perches, contributing a pleasing melody to the tranquil tableau. Jason halted to absorb the scene, shutting his eyes and inhaling deeply, letting the peacefulness envelop him. Momentarily, time appeared to halt, encased in the tender grasp of nature’s majesty. As his walk progressed, a profound sense of calm and thankfulness welled within him, a gentle reminder of autumn's quiet allure. With fall’s arrival, came an aura of regeneration and introspection, hinting at fresh commencements and boundless opportunities.",
    time: 300,
},{
    text: "The dusk crept in over the mirrored surface of the calm lake, imparting a honeyed light across the water's face. The atmosphere was crisp and refreshing, making it an impeccable evening to muse over the day's experiences. Avian melodies echoed faintly from afar, harmonizing with the soft whisper of leaves fluttering in the breeze. A group of swans moved smoothly over the water, their passage leaving behind ripples that shimmered in the declining sunlight. Perched on the sturdy dock, the wood's warmth seeped into me, bringing about a deep sentiment of serenity and satisfaction. The anxieties of life seemed to float away on the sound of water gently caressing the shore. The sky metamorphosed into a canvas of shades, with tints of lavender, gold, and crimson weaving flawlessly together. It was instances like these that highlighted the sheer grace in simplicity. Despite how hectic life may become, there exists a haven for peace and stillness. Breathing deeply, I cherished the moment, aware that these experiences are gemstones of rarity. This evening near the lake would be a lasting memory, a reminder to savor life's peaceful episodes.",
    time: 300,
},{
    text: "The early evening brought a dimming glow to the quiet lake, scattering a mild gleam over the water's expanse. The air felt brisk and clear, an excellent setting for reflecting on the events of the day. Songs of birds resonated softly from far away, blending smoothly with the light rustle of leaves stirred by the wind. A pair of otters moved lazily over the lake, their path creating waves that sparkled in the dwindling light. Resting on the old dock, the warmth of the wood beneath providing comfort, a profound tranquility and satisfaction enveloped me. The day's worries seemed to drift with the soft gurgle of water meeting the shore. The heavens transitioned into a vibrant display of hues, with shades of peach, crimson, and violet merging effortlessly. Moments like these serve as reminders of nature's simple beauty. No matter how frenzied life may become, there is always space for tranquility and calm. Drawing in a deep breath, I relished the moment, understanding that such occasions are both valuable and rare. The twilight by the lake would linger as a cherished memory, a gentle prompt to find happiness in quiet times.",
    time: 300,
},{
    text: "As the sun gradually set over the placid lake, it painted the water's surface with hues of gold. The air was cool and refreshing, the perfect ambiance to ponder over the day's happenings. Birds' melodies filled the air softly, merging with the quiet rustling of leaves in the wind. A group of turtles glided serenely over the water, leaving tiny ripples that shimmered in the fading light. Sitting on the aged dock, the warmth of the wood underneath offered a comforting sense of well-being. Life’s worries seemed to fade away with the sound of waves gently hitting the shore. The sky turned into a masterpiece of pastels, with hints of rose, tangerine, and violet blending harmoniously. Moments like these highlighted the simple yet profound beauty of the world. Regardless of how chaotic life gets, there is always a sanctuary of peace and serenity. Taking a deep breath, I cherished the now, knowing how rare such moments are. This evening by the lakeside would remain a valued memory, reminding me to seek joy in life's serene moments.",
    time: 300,
},{
    text: "As the sun dipped lower over the tranquil waters of the lake, it cast a warm, golden light that seemed to dance across the surface. The air was cool and renewing, an ideal circumstance to think back on the day's events. Bird songs echoed softly from the distance, intermingling with the mild rustling of leaves in the gentle air. A family of swans drifted smoothly over the water, creating waves that glistened in the dimming light. Perched on the wooden dock, the wood's warmth radiating through, I felt an overwhelming sense of peace and satisfaction. The hassles of life seemed to dissipate with the sound of the water gently meeting the shore. The sky shifted into a fantastic spectrum of colors, with shades of pink, orange, and plum intertwining flawlessly. Moments like these emphasized the world's inherent beauty. No matter how hectic life turns, there's always a refuge for calm and serenity. Breathing deeply, I savored the instant, recognizing the rarity of such scenes. This evening by the lake would remain a treasured memory, a testament to finding joy in life’s peaceful intervals.",
    time: 300,
},{
    text: "At dusk, when the setting sun painted gold on the calm lake, the air was cool and clear, perfect for reflecting on the day's adventures. Birds sang softly in the distance, their tunes blending with the gentle rustle of leaves in the breeze. A family of ducks glided across the water, creating delicate ripples that danced in the diminishing light. Sitting on the wooden dock, the warmth beneath me offered a sense of peace and contentment. Life's worries floated away with the gentle lapping of waves against the shore. The sky became a tapestry of colors, with hues of pink, orange, and purple intertwining seamlessly. Moments like these showcased the simple beauty in the world. Despite life's chaos, there is always a space for tranquility. Taking a deep breath, I savored the moment, knowing how precious such experiences are. This evening by the lake would be a cherished memory, a reminder of the joy found in serene moments.",
    time: 300,
},{
    text: "The sunset turned the lake's surface golden as the day ended, the air cool and fresh, ideal for reflecting on the day's occurrences. Bird songs rose softly from afar, mingling with the soft rustling of leaves in the breeze. A family of swans drifted over the water, creating ripples that shimmered in the fading light. Perched on the wooden dock, the warmth beneath me offered peace and contentment. Life's troubles floated away with the sound of waves gently meeting the shore. The sky turned into a blend of pink, orange, and purple hues. Moments like these showcased life's simple beauty. Despite the chaos of life, there's always a place for calm. Taking a deep breath, I enjoyed the moment, aware of how rare such experiences are. This evening by the lake would be a lasting memory, a reminder to appreciate serene moments.",
    time: 300,
},{
    text: "The evening sun bathed the lake in a golden glow, making the air crisp and clear, perfect for reflecting on the day's events. Birds' melodies filled the air softly, intertwined with the light rustling of leaves in the breeze. A family of geese glided effortlessly across the water, creating ripples that shone in the fading light. Sitting on the wooden dock, the warmth beneath me provided a sense of peace and fulfillment. Life's worries seemed to drift with the gentle sound of waves against the shore. The sky turned into a spectrum of colors, with pink, orange, and purple merging seamlessly. Moments like these emphasized the world's simple beauty. Despite the chaos of life, tranquility always finds a place. Breathing deeply, I savored the instant, recognizing the rarity of such scenes. This evening by the lake would be a cherished memory, highlighting the joy found in serene moments.",
    time: 300,
},{
    text: "The setting sun cast a golden hue over the lake, creating a perfect evening for reflecting on the day's events. The air was cool, birds chirped softly, and the leaves rustled gently in the breeze. A family of ducks glided across the water, creating ripples in the fading light. Sitting on the wooden dock, the warmth of the wood beneath me offered peace and contentment. Life's worries seemed to float away with the sound of waves gently hitting the shore. The sky transformed into hues of pink, orange, and purple, blending seamlessly together. Moments like these reminded me of the world's simple beauty. No matter how chaotic life becomes, tranquility always exists. Taking a deep breath, I cherished the moment, knowing how precious such experiences are. This evening by the lake would be a lasting memory, a reminder to find joy in serene moments.",
    time: 300,
},{
    text: "The horizon shimmered with the day’s last light, casting an ethereal glow over the serene water’s surface. The air carried a brisk and invigorating bite, a fitting backdrop for introspection on the day’s encounters. Birdsong chimed softly from afar, mingling beautifully with the gentle rustle of leaves swaying in the breeze. A flock of geese floated gracefully across the pond, their wake forming ripples that twinkled in the waning light. Sitting on the weathered dock, the wood warm on my skin, I felt enveloped by a profound sense of tranquility and satisfaction. The troubles of existence seemed to recede with the rhythm of waves tenderly kissing the shore. The sky evolved into a masterpiece of shades, with greens, blues, and indigos merging effortlessly together. It was these fleeting moments that underscored the innate splendor in living. Regardless of how turbulent life turns, a sanctuary of peace and quietude always remains. Taking a slow, deep inhale, I treasured the present, recognizing that such instances of solace and simplicity are invaluable. This twilight by the lakeside would become a treasured reminiscence, a gentle nudge to seek out serenity within life’s tranquil corners.",
    time: 300,
},]

export default texts;